name: Deploy to VPS

on:
  push:
    branches: [ backend ]  # Change to your main branch name (main, master, etc.)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/surveytools-backend:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/surveytools-backend:latest
          cache-to: type=inline
      
      - name: Create .env file on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            # Create app directory if it doesn't exist
            mkdir -p ~/surveytools-backend
            
            # Create .env file from GitHub secret
            echo "${{ secrets.ENV_FILE }}" > ~/surveytools-backend/.env
      
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            # Pull the latest image
            docker pull ${{ secrets.DOCKER_USERNAME }}/surveytools-backend:latest
            
            # Stop and remove the current container if it exists
            docker stop surveytools-backend || true
            docker rm surveytools-backend || true
            
            # Run the new container with environment variables from .env file
            docker run -d \
              --name surveytools-backend \
              --restart unless-stopped \
              -p 5000:5000 \
              --env-file ~/surveytools-backend/.env \
              ${{ secrets.DOCKER_USERNAME }}/surveytools-backend:latest
            
            # Clean up unused images
            docker image prune -f 